#docker-compose.yaml

services:
  db:
    container_name: "scratch_db"
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      INSTALLER_USERID: ${INSTALLER_USERID}
      INSTALLER_PWD: ${INSTALLER_PWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "${MYSQL_TCP_PORT}:3306"
    volumes:
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
