# all-wf-fork-pub-scheduled_sync_with_upstream-def.yaml
# This work flow does not work for private repositories.
name: Scheduled Sync with Upstream Public Fork

on:
    workflow_call:
        #    inputs:
        #      run_deploy:
        #        description: "Set to 'true' to run the Build-and-Deploy job if a tag was specified."
        #        required:    true
        #        default:     false
        #        type:        boolean
        #      original_owner:
        #        description: "Set to original owner of the fork."
        #        required:    true
        #        default:     ""
        #        type:        string
        #      original_repo_name:
        #        description: "Set to original repo name of the fork."
        #        required:    true
        #        default:     ""
        #        type:        string
        secrets:
            GH_REPO_ACCESS_BEE_MASTER:
                required: true
            GH_REPO_ACCESS_RTE_MASTER:
                required: true
#      MYSQL_PASSWORD:
#        required: true
#      MYSQL_ROOT_PASSWORD:
#        required: true
            ORIGINAL_OWNER:
                required: true
            ORIGINAL_REPO_NAME:
                required: true
#      MYSQL_USER:
#        required: true
#      RELEASE_EMAIL_USER:
#        required: true
#      RELEASE_EMAIL_PASSWORD:
#        required: true

jobs:
    #  Pre-Commit:
    #    uses:    BrightEdgeeServices/devops-automation/.github/workflows/py-pc-precom-all-def.yaml@master
    #    secrets: inherit

    #  CI:
    #    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-ci-pvt_with_docker-def.yaml@master
    #    secrets:
    #      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
    #      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}

    Update-Fork:
        permissions:
            id-token: write
            contents: write
        #if:   ${{ inputs.run_deploy == true }}
        #    needs:
        #      - Pre-Commit
        #      - CI
        uses:
            BrightEdgeeServices/devops-automation/.github/workflows/all-pc-fork-pub-sync_with_upstream-def.yaml@master
            #    with:
        #  run_deploy: ${{ startsWith(github.ref, 'refs/tags/') == true }}
        #      original_owner:     $original_owner
        #      original_repo_name: $original_repo_name
        secrets:
            GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
            GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
            ORIGINAL_OWNER: ${{vars.ORIGINAL_OWNER}}
            ORIGINAL_REPO_NAME: ${{vars.ORIGINAL_REPO_NAME}}
#      RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
#      RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
