# all-wf-fork-pvt-scheduled_sync_with_upstream-def.yaml
# This work flow does not work for private repositories.
name: Scheduled Sync with Upstream Private Fork

on:
    workflow_call:
        secrets:
            GH_REPO_ACCESS_BEE_MASTER:
                required: true
            GH_REPO_ACCESS_RTE_MASTER:
                required: true
            #      MYSQL_PASSWORD:
            #        required: true
            #      MYSQL_ROOT_PASSWORD:
            #        required: true
            #      MYSQL_USER:
            #        required: true
            ORIGINAL_OWNER:
                required: true
            ORIGINAL_REPO_NAME:
                required: true
#      RELEASE_EMAIL_USER:
#        required: true
#      RELEASE_EMAIL_PASSWORD:
#        required: true

jobs:
    Update-Fork:
        permissions:
            id-token: write
            contents: write
        uses:
            BrightEdgeeServices/devops-automation/.github/workflows/all-pc-fork-pvt-sync_with_upstream-def.yaml@master
        secrets:
            GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
            GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
            ORIGINAL_OWNER: ${{secrets.ORIGINAL_OWNER}}
            ORIGINAL_REPO_NAME: ${{secrets.ORIGINAL_REPO_NAME}}
#      RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
#      RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
