# all-wf-fork-pub-scheduled_sync_with_upstream-def.yaml
name: all-wf-fork-pub-scheduled_sync_with_upstream-def

on:
    workflow_call:
        secrets:
            GH_REPO_ACCESS_BEE_MASTER:
                required: true
            GH_REPO_ACCESS_RTE_MASTER:
                required: true
            #      MYSQL_PASSWORD:
            #        required: true
            #      MYSQL_ROOT_PASSWORD:
            #        required: true
            ORIGINAL_OWNER:
                required: true
            ORIGINAL_REPO_NAME:
                required: true
#      MYSQL_USER:
#        required: true
#      RELEASE_EMAIL_USER:
#        required: true
#      RELEASE_EMAIL_PASSWORD:
#        required: true

jobs:
    Update-Fork:
        permissions:
            id-token: write
            contents: write
        #if:   ${{ inputs.run_deploy == true }}
        #    needs:
        #      - Pre-Commit
        #      - CI
        uses:
            BrightEdgeeServices/devops-automation/.github/workflows/all-pc-fork-pub-sync_with_upstream-def.yaml@master
            #    with:
        #  run_deploy: ${{ startsWith(github.ref, 'refs/tags/') == true }}
        #      original_owner:     $original_owner
        #      original_repo_name: $original_repo_name
        secrets:
            # GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
            # GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
            ORIGINAL_OWNER: ${{secrets.ORIGINAL_OWNER}}
            ORIGINAL_REPO_NAME: ${{secrets.ORIGINAL_REPO_NAME}}
            # RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
            # RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
