# py-wf-pypi-pub_no_docker-def.yaml
# ToDo
# This is a copied version and has to be fixed
name: Default PyPI Pipeline

on:
  workflow_call:
    inputs:
      run_deploy:
        description: "Set to 'true' to run the Build-and-Publish-to-PyPI job if a tag was specified."
        required: true
        default: false
        type: boolean
    secrets:
      INSTALLER_USERID:
        required: true
      INSTALLER_PWD:
        required: true
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true
      MYSQL_DATABASE:
        required: true
      MYSQL_HOST:
        required: true
      MYSQL_PASSWORD:
        required: true
      MYSQL_ROOT_PASSWORD:
        required: true
      MYSQL_TCP_PORT:
        required: true
      MYSQL_USER:
        required: true
      PYPI_API_TOKEN_PROD:
        required: true
      RELEASE_EMAIL_USER:
        required: true
      RELEASE_EMAIL_PASSWORD:
        required: true
      VENV_ENVIRONMENT:
        required: true

jobs:
  Pre-Commit:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-precom-all-def.yaml@master
    secrets: inherit

  CI:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-ci-pub-no_docker-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      INSTALLER_USERID: ${{secrets.INSTALLER_USERID }}
      INSTALLER_PWD: ${{secrets.INSTALLER_PWD }}
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{secrets.MYSQL_HOST }}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_TCP_PORT: ${{secrets.MYSQL_TCP_PORT }}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      RELEASE_EMAIL_USER: ${{secrets.RELEASE_EMAIL_USER }}
      RELEASE_EMAIL_PASSWORD: ${{secrets.RELEASE_EMAIL_PASSWORD }}
      VENV_ENVIRONMENT: ${{secrets.VENV_ENVIRONMENT }}

  # Build-and-Publish-to-PyPI:
  #   permissions:
  #     id-token: write
  #     contents: write
  #   if:   ${{ inputs.run_deploy == true }}
  #   needs:
  #     - Pre-Commit
  #     - CI
  #   uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-pypi-default.yaml@master
  #   secrets:
  #     GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
  #     GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
  #     PYPI_API_TOKEN_PROD:       ${{secrets.PYPI_API_TOKEN_PROD }}
  #     RELEASE_EMAIL_PASSWORD:    ${{secrets.RELEASE_EMAIL_PASSWORD }}
  #     RELEASE_EMAIL_USER:        ${{secrets.RELEASE_EMAIL_USER }}
  Detect-PR-Tag:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-pc-pr-all-detect_tag-def.yaml@master
    secrets: inherit

  PR:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    # Run whenever the repository currently has a tag named 'pr'
    if: ${{ always() && needs.Detect-PR-Tag.outputs.has_pr_tag == 'true' }}
    needs:
      - Detect-PR-Tag
      - Pre-Commit
      - CI
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-pc-pr-all-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}

  Cleanup-Delete-pr-Tag:
    permissions:
      contents: write
    if: ${{ always() && needs.Detect-PR-Tag.outputs.has_pr_tag == 'true' }}
    needs:
      - Detect-PR-Tag
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-pc-pr-all-cleanup_tag-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
