# py-wf-pr-pvt-no_docker-def.yaml
name: Pre-Commit, CI and PR (default)

on:
  workflow_call:
    secrets:
      AUTHZ_CACHE_TTL_SEC:
        required: true
      AUTHZ_HOST:
        required: true
      AUTHZ_MYSQL_DATABASE:
        required: true
      AUTHZ_MYSQL_HOST:
        required: true
      AUTHZ_MYSQL_PASSWORD:
        required: true
      AUTHZ_MYSQL_ROOT_PASSWORD:
        required: true
      AUTHZ_MYSQL_TCP_PORT:
        required: true
      AUTHZ_MYSQL_USER:
        required: true
      GH_REPO_ACCESS_BEE_MASTER:
        required: true
      GH_REPO_ACCESS_RTE_MASTER:
        required: true
      INSTALLER_USERID:
        required: true
      INSTALLER_PWD:
        required: true
      MYSQL_DATABASE:
        required: true
      MYSQL_HOST:
        required: true
      MYSQL_PASSWORD:
        required: true
      MYSQL_ROOT_PASSWORD:
        required: true
      MYSQL_TCP_PORT:
        required: true
      MYSQL_USER:
        required: true
      RELEASE_EMAIL_USER:
        required: true
      RELEASE_EMAIL_PASSWORD:
        required: true
      VENV_ENVIRONMENT:
        required: true

jobs:
  Pre-Commit:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-precom-all-def.yaml@master
    secrets: inherit

  CI:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/py-pc-ci-pvt-no_docker-def.yaml@master
    secrets:
      AUTHZ_CACHE_TTL_SEC:       ${{secrets.AUTHZ_CACHE_TTL_SEC}}
      AUTHZ_HOST:                ${{secrets.AUTHZ_HOST}}
      AUTHZ_MYSQL_DATABASE:      ${{secrets.AUTHZ_MYSQL_DATABASE}}
      AUTHZ_MYSQL_HOST:          ${{secrets.AUTHZ_MYSQL_HOST}}
      AUTHZ_MYSQL_PASSWORD:      ${{secrets.AUTHZ_MYSQL_PASSWORD}}
      AUTHZ_MYSQL_ROOT_PASSWORD: ${{secrets.AUTHZ_MYSQL_ROOT_PASSWORD}}
      AUTHZ_MYSQL_TCP_PORT:      ${{secrets.AUTHZ_MYSQL_TCP_PORT}}
      AUTHZ_MYSQL_USER:          ${{secrets.AUTHZ_MYSQL_USER}}
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
      INSTALLER_USERID: ${{secrets.INSTALLER_USERID }}
      INSTALLER_PWD: ${{secrets.INSTALLER_PWD }}
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{secrets.MYSQL_HOST }}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_TCP_PORT: ${{secrets.MYSQL_TCP_PORT }}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      RELEASE_EMAIL_USER: ${{secrets.RELEASE_EMAIL_USER }}
      RELEASE_EMAIL_PASSWORD: ${{secrets.RELEASE_EMAIL_PASSWORD }}
      VENV_ENVIRONMENT: ${{secrets.VENV_ENVIRONMENT }}

  Detect-PR-Tag:
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-pc-pr-all-detect_tag-def.yaml@master
    secrets: inherit

  PR:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    # Run whenever the repository currently has a tag named 'pr'
    if: ${{ always() && needs.Detect-PR-Tag.outputs.has_pr_tag == 'true' }}
    needs:
      - Detect-PR-Tag
      - Pre-Commit
      - CI
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-pc-pr-all-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}

  Cleanup-Delete-pr-Tag:
    permissions:
      contents: write
    if: ${{ always() && needs.Detect-PR-Tag.outputs.has_pr_tag == 'true' }}
    needs:
      - Detect-PR-Tag
    uses: BrightEdgeeServices/devops-automation/.github/workflows/all-pc-pr-all-cleanup_tag-def.yaml@master
    secrets:
      GH_REPO_ACCESS_BEE_MASTER: ${{secrets.GH_REPO_ACCESS_BEE_MASTER }}
      GH_REPO_ACCESS_RTE_MASTER: ${{secrets.GH_REPO_ACCESS_RTE_MASTER }}
